---
- name: service facts
  ansible.builtin.service_facts:

- name: ensure php-fpm is stopped
  ansible.builtin.service:
    name: "php{{ php.version | replace('.','')}}-php-fpm"
    state: stopped
  when: ansible_facts.services is search(php.version | replace('.','') + '-php-fpm.service')
  ignore_errors: true

- name: ensure apache2 is stopped
  ansible.builtin.service:
    name: "apache2"
    state: stopped
  when: ansible_facts.services is search("apache2.service")

- name: import epel repo gpg key
  ansible.builtin.rpm_key:
    key: "{{ php_repo.epel.gpg }}"
    state: present

- name: install epel repo
  ansible.builtin.package:
    name: "{{ php_repo.epel.rpm }}"
    state: present  

- name: import remi repo gpg key
  ansible.builtin.rpm_key:
    key: "{{ php_repo.remi.gpg }}"
    state: present

- name: install remi repo
  ansible.builtin.package:
    name: "{{ php_repo.remi.rpm }}"
    state: present

- name: install php{{ php.version | replace('.','')}}.
  ansible.builtin.package:
    name: "php{{ php.version | replace('.','')}}"
    state: present
    enablerepo: "remi,remi-php{{ php.version | replace('.','')}}"
    update_cache: true
  ignore_errors: true

- name: install php{{ php.version }} modules.
  ansible.builtin.package:
    name: "php{{ php.version | replace('.','')}}-php-{{ item }}"
    state: present
    enablerepo: "remi,remi-php{{ php.version | replace('.','')}}"
    update_cache: true
  ignore_errors: true
  with_items: "{{ php_install.packages}}"

- name: ensure php{{ php.version | replace('.','')}}-php-fpm is started
  ansible.builtin.service:
    name: "php{{ php.version | replace('.','')}}-php-fpm"
    state: started
    enabled: yes