---
- name: ensure dependencies are installed.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ php_install.dependencies.debian }}"

- name: service facts
  ansible.builtin.service_facts:

- name: ensure php-fpm is stopped
  ansible.builtin.service:
    name: "php{{ php.version }}-fpm"
    state: stopped
  when: ansible_facts.services is search(php.version + '-fpm.service')

- name: ensure apache2 is stopped
  ansible.builtin.service:
    name: "apache2"
    state: stopped
  when: ansible_facts.services is search("apache2.service")

- name: install php{{ php.version }}
  ansible.builtin.apt:
    name: "php{{ php.version }}"
    state: present
    update_cache: yes
  ignore_errors: yes  

- name: install php{{ php.version }} packages
  ansible.builtin.apt:
    name: "php{{ php.version }}-{{ item }}"
    state: present
    update_cache: yes
  ignore_errors: yes
  with_items: "{{ php_install.packages }}"

- name: ensure php{{ php.version }}-fpm is started
  ansible.builtin.service:
    name: "php{{ php.version }}-fpm"
    state: started
    enabled: yes