---
- name: ensure dependencies are installed.
  ansible.builtin.apt:
    name: "{{ php_install__dependencies_debian }}"
    state: present
    update_cache: true

- name: add php repository gpg key
  ansible.builtin.apt_key:
    url: "{{ php_install__sury_repo_gpg_key }}"
    state: present
  when: php_install__sury_repo

- name: add php repository
  ansible.builtin.apt_repository:
    repo: "{{ php_install__sury_repo_path }}"
    state: present
    update_cache: yes
  when: php_install__sury_repo

- name: service facts
  ansible.builtin.service_facts:

- name: ensure php-fpm is stopped
  ansible.builtin.service:
    name: "php{{ php_install__version }}-fpm"
    state: stopped
  when: ansible_facts.services is search("-fpm.service")

- name: ensure apache2 is stopped
  ansible.builtin.service:
    name: "apache2"
    state: stopped
  when: ansible_facts.services is search("apache2.service")

- name: install php{{ php_install__version }} packages.
  ansible.builtin.apt:
    name: "php{{ php_install__version }}-{{ item }}"
    state: present
  ignore_errors: yes
  with_items: "{{ php_install__list }}"

- name: ensure php{{ php_install__version }}-fpm is started
  ansible.builtin.service:
    name: "php{{ php_install__version }}-fpm"
    state: started
