---
- name: merge dictionaries
  block:
    - include_vars:
        file: ../../darexsu.php/defaults/main.yml
        name: php_default_vars

    - name: merge default and new dictionaries
      set_fact:
        "{{ item.key }}": "{{ php_default_vars[item.key] | combine(merge[item.key], recursive=True)}}"
      when: php_default_vars[item.key] is defined
      with_dict: "{{ merge }}"

    - name: combine defaults vars with merge dictionary
      set_fact:
        merge: "{{ php_default_vars | combine(merge, recursive=True)}}"
  when: merge is defined

- name: php role is disabled
  meta: end_play
  when: not php.enabled

- name: include php install
  include_tasks: "./tasks/install/php_install__{{ ansible_os_family }}.yml"
  when: php_install.enabled

- name: include php.ini config
  include_tasks: "./tasks/config/php_config__php_ini.yml"
  when:  php_ini.enabled

- name: include "php-fpm config"
  include_tasks: "./tasks/config/php_config__php_fpm.yml"
  when: php_fpm[item.key]['enabled']
  with_dict: "{{ php_fpm }}"