---
- name: include php install from distro
  include_tasks: ./tasks/install/php_install__debian_distro.yml
  when: 
    - php_install
    - ansible_distribution == "Debian"
    - (not php_install__repo or not php_install__repo__sury)

- name: include php install from sury
  include_tasks: ./tasks/install/php_install__debian_sury.yml
  when: 
    - php_install 
    - ansible_distribution == "Debian" 
    - php_install__repo
    - php_install__repo__sury

- name: include php install from distro
  include_tasks: ./tasks/install/php_install__ubuntu_distro.yml
  when:
    - php_install
    - ansible_distribution == "Ubuntu"
    - (not php_install__repo or not php_install__repo__ondrej)

- name: include php install from andrej
  include_tasks: ./tasks/install/php_install__ubuntu_andrej.yml
  when:
    - php_install
    - ansible_distribution == "Ubuntu"
    - php_install__repo
    - php_install__repo__ondrej

- name: include php install from distro
  include_tasks: ./tasks/install/php_install__redhat_distro.yml
  when:
    - php_install
    - ansible_os_family == "RedHat"
    - (not php_install__repo or not php_install__repo__remi)

- name: include php install from remi
  include_tasks: ./tasks/install/php_install__redhat_remi.yml
  when:
    - php_install
    - ansible_os_family == "RedHat"
    - php_install__repo
    - php_install__repo__remi

- name: include php config
  include_tasks: ./tasks/config/php_config__debian.yml
  when:
    - php_config
    - ansible_os_family == "Debian"

- name: include php config remi
  include_tasks: ./tasks/config/php_config__redhat_distro.yml
  when:
    - php_config
    - ansible_os_family == "RedHat"
    - (not php_install__repo or not php_install__repo__remi)

- name: include php config remi
  include_tasks: ./tasks/config/php_config__redhat_remi.yml
  when:
    - php_config
    - ansible_os_family == "RedHat"
    - php_install__repo
    - php_install__repo__remi