---
- name: update php.ini config from template
  template:
    src: "{{ php_config__php_ini__template }}"
    dest: "{{ php_config__repo__remi__php_ini_path }}/{{ php_config__php_ini__file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm redhat remi
  when: php_config__php_ini

- name: ensure web-server user exsist
  block:
    - name: ensure web-server group exsist
      ansible.builtin.group:
        name: "{{ php_config__php_fpm__webserver_group }}"

    - name: ensure web-server user exsist
      ansible.builtin.user:
        name: "{{ php_config__php_fpm__webserver_user }}"
        group: "{{ php_config__php_fpm__webserver_group }}"

- name: ensure directory and user exsist for unix socket
  block:
    - name: ensure web-server group exsist
      ansible.builtin.group:
        name: "{{ php_config__php_fpm__unix_socket__group }}"

    - name: ensure web-server user exsist
      ansible.builtin.user:
        name: "{{ php_config__php_fpm__unix_socket__user }}"
        group: "{{ php_config__php_fpm__unix_socket__group }}"
  when: php_config__php_fpm__unix_socket

- name: remove config
  ansible.builtin.file:
    path: "{{ php_config__repo__remi__pool_path }}/{{ php_config__php_fpm__remove_file }}"
    state: absent  
  notify: restart php-fpm redhat remi
  when: php_config__php_fpm__remove_file and php_config__php_fpm

- name: add webserver config php-fpm-pool
  template:
    src: "{{ php_config__php_fpm__template }}"
    dest: "{{ php_config__repo__remi__pool_path }}/{{ php_config__php_fpm__file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm redhat remi
  when: php_config__php_fpm