---
- name: update php.ini config from template
  template:
    src: "{{ php_ini.src }}"
    dest: "{{ php_ini.path.debian}}{{ php_ini.file }}"
    owner: root
    group: root
    mode: 0644
    backup: "{{ php_ini.backup }}"
  notify: restart php-fpm debian
  when: php_ini.enabled

- name: ensure web-server user exsist
  block:
    - name: ensure web-server group exsist
      ansible.builtin.group:
        name: "{{ php_fpm.vars.webserver_group }}"

    - name: ensure web-server user exsist
      ansible.builtin.user:
        name: "{{ php_fpm.vars.webserver_user }}"
        group: "{{ php_fpm.vars.webserver_group }}"

- name: ensure directory and user exsist for unix socket
  block:
    - name: ensure unix group exsist
      ansible.builtin.group:
        name: "{{ php_fpm.vars.unix_socket.group }}"

    - name: ensure unix user exsist
      ansible.builtin.user:
        name: "{{ php_fpm.vars.unix_socket.user }}"
        group: "{{ php_fpm.vars.unix_socket.group }}"
  when: php_fpm.vars.unix_socket.enabled

- name: remove php-fpm config
  ansible.builtin.file:
    path: "{{ php_fpm.path.debian }}{{ php_fpm.file }}"
    state: absent  
  notify: restart php-fpm debian
  when: php_fpm.enabled and php_fpm.state == "absent"

- name: remove default config
  ansible.builtin.file:
    path: "{{ php_fpm.path.debian }}www.conf"
    state: absent  
  notify: restart php-fpm debian
  when: php_fpm.enabled and php_fpm.remove_default

- name: add webserver config php-fpm-pool
  template:
    src: "{{ php_fpm.src }}"
    dest: "{{ php_fpm.path.debian }}{{ php_fpm.file }}"
    owner: root
    group: root
    mode: 0644
    backup: "{{ php_fpm.backup }}"
  notify: restart php-fpm debian
  when: php_fpm.enabled and php_fpm.state == "present"