---
- name: restart php-fpm debian
  service:
    name: php{{ php_install__version }}-fpm
    state: restarted

- name: restart php-fpm redhat distro
  service:
    name: php-fpm
    state: restarted

- name: restart php-fpm redhat remi
  service:
    name: php{{ php_install__version | replace('.','')}}-php-fpm
    state: restarted