---
- name: Converge
  hosts: all

  pre_tasks:
  - name: Unnessessary command
    ansible.builtin.shell:
      cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
    when: lookup('env', 'ANSIBLE_COMMAND') | length > 0
    
  roles:
    - role: darexsu.php
      # - install
      php_install: true
      php_install__version: "8.0"
      # - config
      php_config: true
      # - config  php.ini
      php_config__php_ini: true
      # - config  php_fpm
      php_config__php_fpm: true
      # - config  php_fpm  tcp_ip_socket
      php_config__php_fpm__tcp_ip_socket: true
      php_config__php_fpm__tcp_ip_socket__listen: "127.0.0.1:9000"