---
- name: Converge
  hosts: all
  
  pre_tasks:
  - name: Unnessessary command
    ansible.builtin.shell:
      cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
    when: lookup('env', 'ANSIBLE_COMMAND') | length > 0     
  
  vars:
    php_merge: 
      php:
        version: "7.4"     
      php_repo:
        enabled: true    
      php_install:
        enabled: true
        packages: [bcmath, common, fpm]    
      php_fpm: 
        enabled: true
        file: ["www.conf"]
        state: "present"
        vars:
          unix_socket:
            enabled: true
            file: "php{{ php.version }}-fpm.sock"
            user: "www-data"
            group: "www-data"   
      php_ini:
        enabled: true

  tasks:
  - name: include role darexsu.php
    include_role: 
      name: darexsu.php