---
- name: Converge
  hosts: all

  pre_tasks:
  - name: Unnessessary command
    ansible.builtin.shell:
      cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
    when: lookup('env', 'ANSIBLE_COMMAND') | length > 0
    
  roles:
    - role: darexsu.php
      # - install
      php_install: true
      php_install__version: "8.0"
      # - install  repo
      php_install__sury_repo: true
      php_install__ondrej_repo: true
      php_install__remi_repo: true
      # - config
      php_config: true
      # - config  php.ini
      php_config__php_ini: true
      # - config  php_fpm
      php_config__php_fpm: true
      # - config  php_fpm  unix socket
      php_config__php_fpm__unix_socket: true
      php_config__php_fpm__unix_socket__user: "username"
      php_config__php_fpm__unix_socket__group: "username"     
      # - config  php_fpm  remove file
      php_config__php_fpm__remove_file: "www.conf"